# 모델 관련 파라미터
d_model: 64
d_state: 256
n_layers: 4
dropout: 0.1
learning_rate: 0.0005 # 5e-4
batch_size: 512
seq_len: 252
input_dim: 8
vae: True

# 데이터 관련 파라미터
data_path: regime_mamba/data/data_full_final.csv
preprocessed: False
target_type: average
target_horizon: 60

# 학습 관련 파라미터
max_epochs: 100
patience: 30
use_onecycle: True
progressive_train: True

#클러스터링 관련 설정
n_clusters: 2
cluster_method: kmeans