# 모델 관련 파라미터
d_model: 250
d_state: 203
n_layers: 6
dropout: 0.074
learning_rate: 8.22e-5
batch_size: 256
seq_len: 453
input_dim: 4

# 데이터 관련 파라미터
data_path: regime_mamba/data/data_average_120_p.csv
preprocessed: True
target_type: average
target_horizon: 120

# 학습 관련 파라미터
max_epochs: 50
patience: 10

#클러스터링 관련 설정
n_clusters: 2
cluster_method: cosine_kmeans