# 모델 관련 파라미터
d_model: 64
d_state: 128
n_layers: 8
dropout: 0.1
learning_rate: 0.0005 # 5e-4
batch_size: 1024
seq_len: 252
input_dim: 10
vae: True

# 데이터 관련 파라미터
data_path: regime_mamba/data/data_full_final.csv
preprocessed: False
target_type: average
target_horizon: 30

# 학습 관련 파라미터
max_epochs: 100
patience: 30
use_onecycle: True
progressive_train: True

#클러스터링 관련 설정
n_clusters: 2
cluster_method: kmeans

results_dir: '/content/drive/MyDrive/train_results'
start_date: '2007-04-20'
total_window_years: 25
train_years: 20
valid_years: 5
clustering_years: 0
forward_months: 36